insert ignore into ad_lang
(name, en_name, short_code)
("Abkhazian","Abkhazian","ab"),
("Afar","Afar","aa"),
("Afrikaans","Afrikaans","af"),
("Albanian","Albanian","sq"),
("Amharic","Amharic","am"),
("Aragonese","Aragonese","an"),
("Armenian","Armenian","hy"),
("Assamese","Assamese","as"),
("Aymara","Aymara","ay"),
("Azerbaijani","Azerbaijani","az"),
("Bashkir","Bashkir","ba"),
("Basque","Basque","eu"),
("Bengali (Bangla)","Bengali (Bangla)","bn"),
("Bhutani","Bhutani","dz"),
("Bihari","Bihari","bh"),
("Bislama","Bislama","bi"),
("Breton","Breton","br"),
("Bulgarian","Bulgarian","bg"),
("Burmese","Burmese","my"),
("Byelorussian (Belarusian)","Byelorussian (Belarusian)","be"),
("Cambodian","Cambodian","km"),
("Catalan","Catalan","ca"),
("Cherokee","Cherokee",""),
("Chewa","Chewa",""),
("Chinese (Simplified)","Chinese (Simplified)","zh-Hans"),
("Chinese (Traditional)","Chinese (Traditional)","zh-Hant"),
("Corsican","Corsican","co"),
("Croatian","Croatian","hr"),
("Czech","Czech","cs"),
("Divehi","Divehi",""),
("Dutch","Dutch","nl"),
("Edo","Edo",""),
("Esperanto","Esperanto","eo"),
("Estonian","Estonian","et"),
("Faeroese","Faeroese","fo"),
("Farsi","Farsi","fa"),
("Fiji","Fiji","fj"),
("Finnish","Finnish","fi"),
("Flemish","Flemish",""),
("Frisian","Frisian","fy"),
("Fulfulde","Fulfulde",""),
("Galician","Galician","gl"),
("Gaelic (Scottish)","Gaelic (Scottish)","gd"),
("Gaelic (Manx)","Gaelic (Manx)","gv"),
("Georgian","Georgian","ka"),
("Greek","Greek","el"),
("Greenlandic","Greenlandic","kl"),
("Guarani","Guarani","gn"),
("Gujarati","Gujarati","gu"),
("Haitian Creole","Haitian Creole","ht"),
("Hausa","Hausa","ha"),
("Hawaiian","Hawaiian",""),
("Hebrew","Hebrew","he"),
("Hebrew","Hebrew", "iw"),
("Hungarian","Hungarian","hu"),
("Ibibio","Ibibio",""),
("Icelandic","Icelandic","is"),
("Ido","Ido","io"),
("Igbo","Igbo",""),
("Indonesian","Indonesian","id"),
("Indonesian","Indonesian", "in"),
("Interlingua","Interlingua","ia"),
("Interlingue","Interlingue","ie"),
("Inuktitut","Inuktitut","iu"),
("Inupiak","Inupiak","ik"),
("Irish","Irish","ga"),
("Javanese","Javanese","jv"),
("Kannada","Kannada","kn"),
("Kanuri","Kanuri",""),
("Kashmiri","Kashmiri","ks"),
("Kazakh","Kazakh","kk"),
("Kinyarwanda (Ruanda)","Kinyarwanda (Ruanda)","rw"),
("Kirghiz","Kirghiz","ky"),
("Kirundi (Rundi)","Kirundi (Rundi)","rn"),
("Konkani","Konkani",""),
("Korean","Korean","ko"),
("Kurdish","Kurdish","ku"),
("Laothian","Laothian","lo"),
("Latin","Latin","la"),
("Latvian (Lettish)","Latvian (Lettish)","lv"),
("Limburgish ( Limburger)","Limburgish ( Limburger)","li"),
("Lingala","Lingala","ln"),
("Lithuanian","Lithuanian","lt"),
("Macedonian","Macedonian","mk"),
("Malagasy","Malagasy","mg"),
("Malay","Malay","ms"),
("Malayalam","Malayalam","ml"),
("Maltese","Maltese","mt"),
("Maori","Maori","mi"),
("Marathi","Marathi","mr"),
("Moldavian","Moldavian","mo"),
("Mongolian","Mongolian","mn"),
("Nauru","Nauru","na"),
("Nepali","Nepali","ne"),
("Norwegian","Norwegian","no"),
("Occitan","Occitan","oc"),
("Oriya","Oriya","or"),
("Oromo (Afaan Oromo)","Oromo (Afaan Oromo)","om"),
("Papiamentu","Papiamentu",""),
("Pashto (Pushto)","Pashto (Pushto)","ps"),
("Punjabi","Punjabi","pa"),
("Quechua","Quechua","qu"),
("Rhaeto-Romance","Rhaeto-Romance","rm"),
("Sami (Lappish)","Sami (Lappish)",""),
("Samoan","Samoan","sm"),
("Sangro","Sangro","sg"),
("Sanskrit","Sanskrit","sa"),
("Serbian","Serbian","sr"),
("Serbo-Croatian","Serbo-Croatian","sh"),
("Sesotho","Sesotho","st"),
("Setswana","Setswana","tn"),
("Shona","Shona","sn"),
("Sichuan Yi","Sichuan Yi","ii"),
("Sindhi","Sindhi","sd"),
("Sinhalese","Sinhalese","si"),
("Siswati","Siswati","ss"),
("Slovak","Slovak","sk"),
("Slovenian","Slovenian","sl"),
("Somali","Somali","so"),
("Sundanese","Sundanese","su"),
("Swahili (Kiswahili)","Swahili (Kiswahili)","sw"),
("Syriac","Syriac",""),
("Tagalog","Tagalog","tl"),
("Tajik","Tajik","tg"),
("Tamazight","Tamazight",""),
("Tamil","Tamil","ta"),
("Tatar","Tatar","tt"),
("Telugu","Telugu","te"),
("Thai","Thai","th"),
("Tibetan","Tibetan","bo"),
("Tigrinya","Tigrinya","ti"),
("Tonga","Tonga","to"),
("Tsonga","Tsonga","ts"),
("Turkish","Turkish","tr"),
("Turkmen","Turkmen","tk"),
("Twi","Twi","tw"),
("Uighur","Uighur","ug"),
("Ukrainian","Ukrainian","uk"),
("Urdu","Urdu","ur"),
("Uzbek","Uzbek","uz"),
("Venda","Venda",""),
("Vietnamese","Vietnamese","VI"),
("Volap�k","Volap�k","vo"),
("Wallon","Wallon","wa"),
("Welsh","Welsh","cy"),
("Wolof","Wolof","wo"),
("Xhosa","Xhosa","xh"),
("Yi","Yi",""),
("Yiddish","Yiddish","yi"),
("Yiddish","Yiddish", "ji"),
("Yoruba","Yoruba","yo"),
("Zulu","Zulu","zu");